# newest version docker
version: "3"

services:
  reactjs:
    container_name: reactjs-product
    build:
      context: ./reactjs
      dockerfile: Dockerfile
    ports:
      - 132:80
    volumes:
      - .:/app
    depends_on:
      - server
    restart: always

  nextjs:
    container_name: nextjs-product
    build:
      context: ./nextjs
      dockerfile: Dockerfile
    ports:
      - 333:3000

  nginx:
    container_name: reactjs-nginx
    build:
      context: ./nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "113:80"
    depends_on:
      - server
