name: test-ci-cd

on:
  push:
    branches:
      - "main"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: SETUP DOCKER BUILD
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build and PUSH DOCKER IMAGE CLIENT SERVER
        uses: docker/build-push-action@v2
        with:
          context: ./reactjs
          file: ./reactjs/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/reactjs-product
      - name: Verify
        run: echo "Đã thành công"
  deploy:
    # chỗ này có thể có hoặc ko needs là chờ 1 job nào đó xong r làm tiếp
    needs: docker
    runs-on: ubuntu-latest
    # cấp quyền để chạy scripts
    permissions:
      packages: write
      contents: read
    steps:
      # tạo 1 step deploy
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          # cấu hình connect to server
          host: ${{ secrets.BUILD_HOSTING_NAME }}
          username: root
          password: ${{ secrets.BUILD_SSH_PASSWORD}}
          port: 22
          script_stop: true
          # script connect -> trỏ đến folder learn_github -> pull new code --> run docker compose up -d --build để run code mới trên server
          script: |

            echo "connect to  root@${{ secrets.BUILD_HOSTING_NAME }} "

            cd test-ci-cd

            git pull

            echo " pull soucre code success"

            docker compose up -d --build

            echo " docker compose success"
