name: test-ci-cd

on:
  push:
    branches:
      - "main"
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: SETUP DOCKER BUILD
        uses: docker/setup-buildx-action@v1
        id: buildx

      - name: Build and PUSH DOCKER IMAGE CLIENT SERVER
        uses: docker/build-push-action@v2
        with:
          context: ./reactjs
          file: ./reactjs/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/reactjs-product
      - name: Verify
        run: echo "Đã thành công"
